version: '3.8'
services:
  drag-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - CHOKIDAR_USEPOLLING=true  
    
# version: '3.8'

# services:
#   react-app:
#     image: amanguptak/drag-docker:latest
#     networks:
#       - react-net

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the custom Nginx config
#       - react-app-build:/usr/share/nginx/html        # Mount the built React app
#     depends_on:
#       - react-app
#     networks:
#       - react-net

# networks:
#   react-net:

# volumes:
#   react-app-build:

